spring:
  datasource:
    url: ${SERVER_DB_URL}
    username: ${SERVER_DB_USER}
    password: ${SERVER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"