spring:
  datasource:
    url: ${SERVER_DB_URL}
    username: ${SERVER_DB_USER}
    password: ${SERVER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"

keycloak:
  realm: task_tracker
  resource: task_tracker_app
  auth-server-url: ${AUTH_SERVER}/auth
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true